name: neurophox
channels:
    - pytorch-nightly
    - conda-forge
    - anaconda
dependencies:
    - python=3.7 # or 2.7
    - numpy
    - scipy=1.4.1
    - tensorflow=2.2.*
    - pytorch=1.7.*
    - sphinx-autodoc-typehints
